apiVersion:
kind: Deployment
metadata:
  name: enc-dec-uem
spec:
  selector:
    matchLabels:
      run: enc_dec_uem
  template:
    metadata:
      labels:
        run: enc_dec_uem
    spec:
      containers:
        - name: enc_dec_uem
          image: jp2.icr.io/enc_dec_uem/enc_dec_uem:1
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: icr
